### ISSUE TITLE
Should we announce stream/song info before playing?

### ISSUE THREAD

**Issue by alecpm** [KCRW-org/KCRW-Alexa-Skill#1]
Right now play commands ("Open KCRW"; "Ask KCRW to play ...") just start up an audio stream. Should they announce the current show/program (or song for E24)? Even if it doesn't don't announce this info should it display a card with the information in the Alexa app UI or on Echo Show?

For Eclectic 24, should song card displays mention Eclectic 24, or just the song, artist, album info (the skill name is always included).

**Comment by kcrw** [comment]
Let's start with the below. We may refine with further testing:

- For the audio streams, have it announce show and episode name. 
- On the UI, it should display  as much as possible, so- show, episode, song name, etc
- For E24 it should mention Eclectic 24, artist and song.

**Comment by alecpm** [comment]
One thing to note: the card displays are one per request, so if we display the song at startup it will stay up as the current card until a new request is made. We can't for example poll to display songs as they come in.

**Comment by kcrw** [comment]
I think in that case we'll want the card to display show name or in the case of E24 "KCRW's Eclectic 24"

**Comment by alecpm** [comment]
This is implemented in both the KCRW and KCRW Beta skills.
