### ISSUE TITLE
Which streams to use?

### ISSUE THREAD

**Issue by alecpm** [KCRW-org/KCRW-Alexa-Skill#3]
The skill currently uses the AAC streams (128k). Should we be using the MP3 streams instead? Or maybe HLS (not sure if we have HLS on StreamGuys for more than the simulcast stream)?

**Comment by kcrw** [comment]
We probably want to create a new stream alias specifically for Alexa for analytics purposes. For now use any of them until we can get those set up.

**Comment by seankcrw** [comment]
Aliases are set up:

For KCRW Live/On Air:

kcrw.streamguys1.com/kcrw_192k_mp3_on_air-alexa
kcrw.streamguys1.com/kcrw_128k_mp3_on_air-alexa
kcrw.streamguys1.com/kcrw_128k_aac_on_air-alexa

For KCRW Eclectic 24:

kcrw.streamguys1.com/kcrw_192k_mp3_e24-alexa
kcrw.streamguys1.com/kcrw_128k_mp3_e24-alexa
kcrw.streamguys1.com/kcrw_128k_aac_e24-alexa

**Comment by alecpm** [comment]
The new streams (AAC only) are now being used by the Skill, ideally we should have a custom news stream as well.

**Comment by seankcrw** [comment]
I've edited my comment above to include News 24.

**Comment by alecpm** [comment]
Updated streams are all live now.
