### ISSUE TITLE
Need Developer Account for KCRW

### ISSUE THREAD

**Issue by alecpm** [KCRW-org/KCRW-Alexa-Skill#4]
One of KCRW's Amazon accounts (either `kcrwdigital` or `webmaster`) needs to be setup for hosting an Alexa skill. Enable the account here:

https://developer.amazon.com/

I'm currently hosting the beta app on my personal developer account, but the AWS Lambda web service powering it is running on the `webmaster` AWS account where all our server resources are hosted. The skill itself can be on either account.

Once that's done I'll migrate the app over to the new developer account.

**Comment by kcrw** [comment]
We're signed up. Let me know if you need login credentials.

**Comment by alecpm** [comment]
I have credentials for both, is it on `kcrwdigital` or `webmaster`?

**Comment by kcrw** [comment]
kcrwdigital
