### ISSUE TITLE
Skill Icons

### ISSUE THREAD

**Issue by alecpm** [KCRW-org/KCRW-Alexa-Skill#5]
The skill needs 108 x 108px and 512 x 512px icons to display in the skill store. Right now I'm using badly scaled versions of the website footer logo. You should be able to replace those icons directly from the GitHub UI.

**Comment by alecpm** [comment]
The new KCRW hosted skill is here:

https://developer.amazon.com/edw/home.html#/skill/amzn1.ask.skill.1a8abcbc-1fca-4f61-b87e-12da026087ce/en_US/info

Icons can be added/updated in the publishing info there.

**Comment by seankcrw** [comment]
Icons are now added.

**Comment by alecpm** [comment]
Would it be possible to attach the icons used here for reference, and perhaps provide a variation for future beta versions?

**Comment by seankcrw** [comment]
Icons attached along with beta variations
![kcrw-logo_108](https://user-images.githubusercontent.com/31420357/29836591-881f3206-8caa-11e7-9536-aef201ce5a49.png)
![kcrw-logo_512](https://user-images.githubusercontent.com/31420357/29836593-88217430-8caa-11e7-9879-5644d8ee7b78.png)
![kcrw-logo-beta_108](https://user-images.githubusercontent.com/31420357/29836594-88579a88-8caa-11e7-8d38-a1d14d1133be.png)
![kcrw-logo-beta_512](https://user-images.githubusercontent.com/31420357/29836592-8820db74-8caa-11e7-8112-500dd31d26b4.png)
