### ISSUE TITLE
Asking Alexa for song name does not work via TuneIn E24 stream

### ISSUE THREAD

**Issue by seankcrw** [KCRW-org/KCRW-Alexa-Skill#8]

**Comment by alecpm** [comment]
Unfortunately, there's no way we can interact with the stream info when it's being played by TuneIn or iHeartRadio or any means other than by our custom skill. You can use "Alexa, ask KCRW what's playing" (or similar), but that will always tell you what's on the Simulcast stream unless you are using the skill to listen to another stream.

**Comment by seankcrw** [comment]
Good to know. Thanks!
